import '../src/db/index.js';
import { db } from '../src/db/index.js';

// Ensure migrations applied (in case user runs seed independently)
import '../src/db/migrate.js';

// Find an employer to own jobs or create one
let employer = db.prepare("SELECT id FROM users WHERE role='employer' LIMIT 1").get();
if (!employer) {
  const hash = require('bcryptjs').hashSync('employer123',10);
  const info = db.prepare('INSERT INTO users (email, password_hash, role, name) VALUES (?,?,?,?)')
    .run('seed-employer@portal.local', hash, 'employer', 'Seed Employer');
  employer = { id: info.lastInsertRowid };
  console.log('Created seed employer: seed-employer@portal.local / employer123');
}

// We now allow incremental seeding: insert any missing predefined jobs by title.
const existingTitlesRow = db.prepare('SELECT title FROM jobs').all();
const existingTitles = new Set(existingTitlesRow.map(r => r.title));

const today = new Date();
function daysFromNow(d){const dt = new Date(today); dt.setDate(dt.getDate()+d); return dt.toISOString().slice(0,10);} // yyyy-mm-dd

const initialJobs = [
  {
    title: 'Assistant Professor - Computer Science', institution_name:'IIT Delhi', organization_type:'public_university', employment_type:'full_time', subject:'Computer Science', grade_level:'UG/PG', city:'New Delhi', location:'Delhi', min_experience:2, education_required:'PhD in Computer Science (submitted/awarded)', skills_required:'Algorithms,Distributed Systems,Research Publications', pay_scale:'Level 12 Pay Matrix (Rs. 1,01,500 – 1,67,400)', application_deadline: daysFromNow(45), remote_allowed:0, description:'Faculty position driving research & teaching in core CS areas.', responsibilities:'Teach 2 courses/semester; Guide B.Tech/M.Tech theses; Publish in top-tier venues; Departmental duties', requirements:'Strong publication record (IEEE/ACM); PhD from reputed institute; Demonstrated teaching aptitude', benefits:'DA, HRA, LTC, Medical, Professional Development Grant', salary_min:101500, salary_max:167400
  },
  { title:'PGT Physics', institution_name:'Kendriya Vidyalaya', organization_type:'government', employment_type:'full_time', subject:'Physics', grade_level:'XI-XII', city:'Mumbai', location:'Maharashtra', min_experience:1, education_required:'Master\'s in Physics + B.Ed', skills_required:'Classroom Management,Curriculum Planning,Lab Safety', pay_scale:'Rs. 47,600 – 1,51,100 (Level 8)', application_deadline: daysFromNow(30), remote_allowed:0, description:'Senior secondary physics teaching role.', responsibilities:'Deliver NCERT-aligned lessons; Conduct practicals; Mentor students for boards', requirements:'Master in Physics with 50%+; B.Ed; CTET preferred', benefits:'Govt allowances, PF, Pension (NPS)', salary_min:47600, salary_max:151100 },
  { title:'Lecturer - Mechanical Engineering', institution_name:'Government Polytechnic Pune', organization_type:'government', employment_type:'contract', subject:'Mechanical Engineering', grade_level:'Diploma', city:'Pune', location:'Maharashtra', min_experience:0, education_required:'B.E./B.Tech Mechanical (First Class)', skills_required:'Thermodynamics,CAD/CAM,Workshop Practice', pay_scale:'Consolidated Rs. 42,000 / month', application_deadline: daysFromNow(20), remote_allowed:0, description:'Contract lecturer for diploma mech Engg.', responsibilities:'Deliver theory & practical sessions; Assessment & student mentoring', requirements:'First class degree; Industry exposure desirable', benefits:'Consolidated pay, experience certificate', salary_min:40000, salary_max:45000 },
  { title:'Assistant Professor - Commerce', institution_name:'Deemed University (Private)', organization_type:'deemed', employment_type:'full_time', subject:'Commerce', grade_level:'UG', city:'Chennai', location:'Tamil Nadu', min_experience:1, education_required:'PhD / NET / SET in Commerce', skills_required:'Accounting,Finance,Research Guidance', pay_scale:'As per UGC + incentives', application_deadline: daysFromNow(35), remote_allowed:0, description:'Teaching core commerce papers and guiding projects.', responsibilities:'Teach 16 credits/semester; Research & accreditation support', requirements:'PhD or NET; Publication in peer-reviewed journal', benefits:'PF, Gratuity, Housing Allowance', salary_min:60000, salary_max:90000 },
  { title:'Senior Faculty - Mathematics', institution_name:'National Coaching Institute', organization_type:'private', employment_type:'contract', subject:'Mathematics', grade_level:'JEE/NEET Prep', city:'Hyderabad', location:'Telangana', min_experience:3, education_required:'M.Sc Mathematics / IIT Graduate', skills_required:'Problem Solving,Exam Strategy,Content Creation', pay_scale:'Rs. 10–18 LPA', application_deadline: daysFromNow(25), remote_allowed:0, description:'Coaching institute faculty for competitive exams.', responsibilities:'Develop advanced problem sets; Deliver 12 hrs/week lectures', requirements:'Strong track record in JEE coaching', benefits:'Performance bonus, Relocation support', salary_min:800000, salary_max:1800000 },
  { title:'TGT English', institution_name:'Residential CBSE School', organization_type:'private', employment_type:'full_time', subject:'English', grade_level:'VI-X', city:'Jaipur', location:'Rajasthan', min_experience:2, education_required:'B.A / M.A English + B.Ed', skills_required:'Literature,Communication,Student Mentoring', pay_scale:'Rs. 40,000 – 55,000 / month + accommodation', application_deadline: daysFromNow(28), remote_allowed:0, description:'Teaching English with focus on holistic development.', responsibilities:'Plan lessons; Co-curricular literary activities', requirements:'Fluency & CBSE experience', benefits:'On-campus housing, Meals, PF', salary_min:40000, salary_max:55000 },
  { title:'Research Associate - Biomedical', institution_name:'National Research Institute', organization_type:'government', employment_type:'temporary', subject:'Biomedical', grade_level:'Research', city:'Bengaluru', location:'Karnataka', min_experience:0, education_required:'M.Tech Biomedical / GATE Qualified', skills_required:'Data Analysis,Lab Techniques,Documentation', pay_scale:'Rs. 31,000 – 35,000 / month + HRA', application_deadline: daysFromNow(18), remote_allowed:0, description:'Assist funded biomedical device project.', responsibilities:'Data collection; Prototype testing; Reporting', requirements:'GATE valid score; Analytical skills', benefits:'HRA, Travel support', salary_min:31000, salary_max:35000 },
  { title:'Visiting Professor - Artificial Intelligence', institution_name:'International School Bangalore', organization_type:'international_school', employment_type:'visiting', subject:'AI', grade_level:'IB DP', city:'Bengaluru', location:'Karnataka', min_experience:8, education_required:'PhD / Industry Expert', skills_required:'Machine Learning,Ethics,Project Mentoring', pay_scale:'Honorarium per module', application_deadline: daysFromNow(50), remote_allowed:1, description:'Short-term visiting faculty for advanced AI module.', responsibilities:'Deliver intensive module; Guide capstone projects', requirements:'Extensive ML portfolio; Teaching aptitude', benefits:'Travel & accommodation', salary_min:0, salary_max:0 },
  { title:'Assistant Professor - Law', institution_name:'National Law University', organization_type:'public_university', employment_type:'full_time', subject:'Law', grade_level:'UG/PG', city:'Bhopal', location:'Madhya Pradesh', min_experience:2, education_required:'LLM + NET / PhD', skills_required:'Jurisprudence,Research,Case Method', pay_scale:'UGC Scale Level 10', application_deadline: daysFromNow(40), remote_allowed:0, description:'Teach core and elective law courses.', responsibilities:'Teach; Moot supervision; Research & publications', requirements:'NET/PhD; Publications', benefits:'DA, HRA, Research grants', salary_min:57700, salary_max:182400 },
  { title:'Primary Teacher - Rural Education Program', institution_name:'Education NGO', organization_type:'ngo', employment_type:'full_time', subject:'General', grade_level:'Primary', city:'Varanasi', location:'Uttar Pradesh', min_experience:1, education_required:'D.El.Ed / B.Ed', skills_required:'Multi-grade Teaching,Community Engagement', pay_scale:'Rs. 22,000 – 28,000 / month', application_deadline: daysFromNow(22), remote_allowed:0, description:'Deliver foundational literacy & numeracy in rural cluster.', responsibilities:'Lesson delivery; Community mobilization', requirements:'Passion for rural education', benefits:'Travel allowance, Training', salary_min:22000, salary_max:28000 },
  { title:'Faculty - Data Science', institution_name:'EdTech Startup', organization_type:'private', employment_type:'full_time', subject:'Data Science', grade_level:'Professional', city:'Bengaluru', location:'Karnataka', min_experience:3, education_required:'M.Tech / MS / Equivalent', skills_required:'Python,ML,Statistics,Cloud', pay_scale:'Rs. 12 – 20 LPA + ESOPs', application_deadline: daysFromNow(32), remote_allowed:1, description:'Design & deliver data science curriculum for professionals.', responsibilities:'Curriculum design; Live sessions; Mentorship', requirements:'Industry experience 3+ yrs', benefits:'ESOP, Remote flexibility', salary_min:1200000, salary_max:2000000 },
  { title:'Assistant Professor - Civil Engineering', institution_name:'NIT Trichy', organization_type:'public_university', employment_type:'full_time', subject:'Civil Engineering', grade_level:'UG/PG', city:'Tiruchirappalli', location:'Tamil Nadu', min_experience:1, education_required:'PhD (Civil) with B.Tech/M.Tech', skills_required:'Structures,Geotech,Research', pay_scale:'Level 12 Pay Matrix', application_deadline: daysFromNow(55), remote_allowed:0, description:'Civil Engg faculty for teaching & research.', responsibilities:'Teach; Lab supervision; Sponsored projects', requirements:'PhD; Publications in SCI journals', benefits:'Govt perks, CPDA', salary_min:101500, salary_max:167400 },
  { title:'PRT (General)', institution_name:'Army Public School', organization_type:'government', employment_type:'contract', subject:'General', grade_level:'Primary', city:'Lucknow', location:'Uttar Pradesh', min_experience:1, education_required:'Graduate + D.El.Ed / B.Ed + CTET', skills_required:'Pedagogy,Child Psychology', pay_scale:'Rs. 32,000 – 38,000 / month', application_deadline: daysFromNow(26), remote_allowed:0, description:'Primary teacher for core subjects.', responsibilities:'Class teaching; Co-scholastic activities', requirements:'CTET qualified; Good communication', benefits:'EPF, Canteen facilities', salary_min:32000, salary_max:38000 },
  { title:'Assistant Professor - Psychology', institution_name:'State University', organization_type:'public_university', employment_type:'full_time', subject:'Psychology', grade_level:'UG/PG', city:'Kolkata', location:'West Bengal', min_experience:2, education_required:'PhD/NET in Psychology', skills_required:'Counseling,Research Methods', pay_scale:'UGC Scale', application_deadline: daysFromNow(38), remote_allowed:0, description:'Teach & guide PG theses in psychology.', responsibilities:'Teach; Research supervision; Counseling cell', requirements:'NET/PhD; Publication record', benefits:'Medical, Leave travel', salary_min:57700, salary_max:120000 },
  { title:'Guest Faculty - Fine Arts', institution_name:'State College of Arts', organization_type:'government', employment_type:'guest', subject:'Fine Arts', grade_level:'UG', city:'Ahmedabad', location:'Gujarat', min_experience:3, education_required:'MFA / Equivalent', skills_required:'Studio Instruction,Art History', pay_scale:'Rs. 1,500 per lecture (honorarium)', application_deadline: daysFromNow(12), remote_allowed:0, description:'Guest lectures in painting & art history.', responsibilities:'Conduct studios; Portfolio reviews', requirements:'MFA; Portfolio', benefits:'Honorarium only', salary_min:0, salary_max:0 }
];

// Additional 15 jobs (new subjects, mostly Bengaluru / Karnataka focus)
const additionalJobs = [
  { title:'Assistant Professor - Biotechnology', institution_name:'Biotech Research University', organization_type:'public_university', employment_type:'full_time', subject:'Biotechnology', grade_level:'UG/PG', city:'Bengaluru', location:'Karnataka', min_experience:2, education_required:'PhD / NET in Biotechnology', skills_required:'Molecular Biology,Genomics,Research Writing', pay_scale:'UGC Scale Level 11', application_deadline: daysFromNow(48), remote_allowed:0, description:'Teach and supervise biotech labs & projects.', responsibilities:'Lectures; Lab supervision; Grant proposals', requirements:'PhD with publications', benefits:'DA, HRA, Research grants', salary_min:68900, salary_max:205500 },
  { title:'Faculty - Cloud Computing', institution_name:'EdTech Professional Academy', organization_type:'private', employment_type:'full_time', subject:'Cloud Computing', grade_level:'Professional', city:'Bengaluru', location:'Karnataka', min_experience:3, education_required:'B.Tech/M.Tech or Equivalent', skills_required:'AWS,DevOps,Containers,Architecture', pay_scale:'Rs. 14 – 22 LPA', application_deadline: daysFromNow(27), remote_allowed:1, description:'Deliver cloud curriculum & mentor learners.', responsibilities:'Curriculum design; Live sessions; Capstone review', requirements:'Industry cloud certs (AWS/Azure)', benefits:'ESOP, Remote flexibility', salary_min:1400000, salary_max:2200000 },
  { title:'TGT Hindi', institution_name:'CBSE Day School', organization_type:'private', employment_type:'full_time', subject:'Hindi', grade_level:'VI-X', city:'Bengaluru', location:'Karnataka', min_experience:2, education_required:'B.A Hindi + B.Ed', skills_required:'Language Pedagogy,Assessment', pay_scale:'Rs. 38,000 – 50,000 / month', application_deadline: daysFromNow(21), remote_allowed:0, description:'Middle school Hindi teaching role.', responsibilities:'Lesson delivery; Literary activities', requirements:'B.Ed & CBSE experience', benefits:'PF, Medical', salary_min:38000, salary_max:50000 },
  { title:'Sports / Physical Education Teacher', institution_name:'Residential Sports School', organization_type:'private', employment_type:'full_time', subject:'Physical Education', grade_level:'VI-XII', city:'Bengaluru', location:'Karnataka', min_experience:1, education_required:'B.P.Ed / M.P.Ed', skills_required:'Fitness Training,Sports Management', pay_scale:'Rs. 35,000 – 55,000 / month + accommodation', application_deadline: daysFromNow(24), remote_allowed:0, description:'Lead sports & fitness program.', responsibilities:'Training schedules; Inter-school events', requirements:'National level participation preferred', benefits:'Housing, Meals, PF', salary_min:35000, salary_max:55000 },
  { title:'Assistant Professor - Statistics', institution_name:'City University Bengaluru', organization_type:'deemed', employment_type:'full_time', subject:'Statistics', grade_level:'UG/PG', city:'Bengaluru', location:'Karnataka', min_experience:1, education_required:'PhD / NET in Statistics', skills_required:'Probability,Data Analysis,R Programming', pay_scale:'As per UGC + incentives', application_deadline: daysFromNow(34), remote_allowed:0, description:'Teach statistics & guide analytics projects.', responsibilities:'Lectures; Project supervision; Research', requirements:'NET/PhD; Publications', benefits:'PF, Research allowance', salary_min:60000, salary_max:90000 },
  { title:'Primary Teacher - Kannada', institution_name:'Trust-run School', organization_type:'ngo', employment_type:'full_time', subject:'Kannada', grade_level:'Primary', city:'Bengaluru Rural', location:'Karnataka', min_experience:1, education_required:'D.El.Ed / B.Ed Kannada', skills_required:'Language Teaching,Community Engagement', pay_scale:'Rs. 25,000 – 32,000 / month', application_deadline: daysFromNow(19), remote_allowed:0, description:'Deliver foundational Kannada literacy.', responsibilities:'Multi-grade teaching; Community outreach', requirements:'Local language fluency', benefits:'Travel allowance, Training', salary_min:25000, salary_max:32000 },
  { title:'Lecturer - Environmental Science', institution_name:'Green Tech College', organization_type:'private', employment_type:'contract', subject:'Environmental Science', grade_level:'UG', city:'Bengaluru', location:'Karnataka', min_experience:0, education_required:'M.Sc Environmental Science', skills_required:'Ecology,Field Studies,Data Collection', pay_scale:'Rs. 42,000 – 48,000 / month', application_deadline: daysFromNow(23), remote_allowed:0, description:'Teach core environmental papers.', responsibilities:'Lectures; Field trips; Lab sessions', requirements:'Strong academic record', benefits:'PF, Health insurance', salary_min:42000, salary_max:48000 },
  { title:'Visiting Professor - Cybersecurity', institution_name:'Global Tech Institute', organization_type:'international_school', employment_type:'visiting', subject:'Cybersecurity', grade_level:'Professional', city:'Bengaluru', location:'Karnataka', min_experience:7, education_required:'Industry Expert / PhD', skills_required:'Network Security,Governance,Pen Testing', pay_scale:'Honorarium per module', application_deadline: daysFromNow(52), remote_allowed:1, description:'Deliver intensive cybersecurity specialization module.', responsibilities:'Workshops; Project mentorship', requirements:'Demonstrated industry leadership', benefits:'Travel & accommodation', salary_min:0, salary_max:0 },
  { title:'Assistant Professor - Nursing', institution_name:'Allied Health Sciences College', organization_type:'public_university', employment_type:'full_time', subject:'Nursing', grade_level:'UG', city:'Bengaluru', location:'Karnataka', min_experience:2, education_required:'M.Sc Nursing', skills_required:'Clinical Training,Patient Care,Lab Management', pay_scale:'State Scale + allowances', application_deadline: daysFromNow(36), remote_allowed:0, description:'Teach nursing theory & supervise clinical practice.', responsibilities:'Lectures; Clinical rounds; Evaluations', requirements:'Council registration', benefits:'Medical, PF', salary_min:55000, salary_max:78000 },
  { title:'Faculty - Robotics & Automation', institution_name:'Innovation Skill Hub', organization_type:'private', employment_type:'full_time', subject:'Robotics', grade_level:'Professional', city:'Bengaluru', location:'Karnataka', min_experience:2, education_required:'B.Tech/M.Tech Mechatronics / Robotics', skills_required:'Embedded Systems,Control Systems,Prototyping', pay_scale:'Rs. 10 – 16 LPA', application_deadline: daysFromNow(29), remote_allowed:0, description:'Deliver applied robotics courses.', responsibilities:'Curriculum projects; Lab facilitation', requirements:'Hands-on prototyping portfolio', benefits:'Startup culture perks', salary_min:1000000, salary_max:1600000 },
  { title:'PGT Sanskrit', institution_name:'Heritage Senior School', organization_type:'private', employment_type:'full_time', subject:'Sanskrit', grade_level:'XI-XII', city:'Bengaluru', location:'Karnataka', min_experience:2, education_required:'M.A Sanskrit + B.Ed', skills_required:'Classical Texts,Grammar,Pronunciation', pay_scale:'Rs. 45,000 – 60,000 / month', application_deadline: daysFromNow(26), remote_allowed:0, description:'Senior secondary Sanskrit teaching.', responsibilities:'Lesson delivery; Cultural activities', requirements:'Strong linguistic command', benefits:'PF, Bonus', salary_min:45000, salary_max:60000 },
  { title:'Lecturer - Graphic Design', institution_name:'Design & Media College', organization_type:'private', employment_type:'full_time', subject:'Graphic Design', grade_level:'UG', city:'Bengaluru', location:'Karnataka', min_experience:1, education_required:'B.Des / M.Des', skills_required:'Branding,Typography,Digital Tools', pay_scale:'Rs. 55,000 – 80,000 / month', application_deadline: daysFromNow(31), remote_allowed:1, description:'Teach design studio courses & mentor portfolios.', responsibilities:'Studios; Critiques; Portfolio review', requirements:'Industry portfolio', benefits:'Health, Conference support', salary_min:55000, salary_max:80000 },
  { title:'Assistant Professor - Entrepreneurship', institution_name:'Startup School Bengaluru', organization_type:'deemed', employment_type:'full_time', subject:'Entrepreneurship', grade_level:'UG/PG', city:'Bengaluru', location:'Karnataka', min_experience:3, education_required:'MBA / PhD (Mgmt)', skills_required:'Venture Creation,Innovation,Case Teaching', pay_scale:'Rs. 9 – 15 LPA', application_deadline: daysFromNow(37), remote_allowed:0, description:'Teach entrepreneurship & incubator support.', responsibilities:'Courses; Startup mentoring; Case development', requirements:'Startup / investment experience', benefits:'Incubator network access', salary_min:900000, salary_max:1500000 },
  { title:'Music Teacher - Western Instruments', institution_name:'International Arts School', organization_type:'international_school', employment_type:'part_time', subject:'Music', grade_level:'K-12', city:'Bengaluru', location:'Karnataka', min_experience:2, education_required:'Grade 8 (ABRSM/Trinity) or Equivalent', skills_required:'Piano,Guitar,Ensemble Direction', pay_scale:'Hourly + performance incentives', application_deadline: daysFromNow(22), remote_allowed:0, description:'Teach instrument & ensemble sessions.', responsibilities:'Classes; Recital preparation', requirements:'Performance portfolio', benefits:'Performance bonuses', salary_min:0, salary_max:0 },
  { title:'Hospitality Management Instructor', institution_name:'Vocational Skills Institute', organization_type:'ngo', employment_type:'contract', subject:'Hospitality', grade_level:'Vocational', city:'Bengaluru', location:'Karnataka', min_experience:1, education_required:'Diploma / Degree in Hospitality', skills_required:'Front Office,Food Service,Training', pay_scale:'Rs. 30,000 – 40,000 / month', application_deadline: daysFromNow(18), remote_allowed:0, description:'Deliver skill modules in hospitality.', responsibilities:'Practical demos; Soft skills coaching', requirements:'Industry exposure', benefits:'Travel allowance', salary_min:30000, salary_max:40000 },
  { title:'Assistant Professor - Cyber Law', institution_name:'Tech Law Institute', organization_type:'private', employment_type:'full_time', subject:'Cyber Law', grade_level:'PG', city:'Bengaluru', location:'Karnataka', min_experience:2, education_required:'LLM (Cyber/IT Law)', skills_required:'IT Act,Compliance,Policy', pay_scale:'Rs. 70,000 – 1,10,000 / month', application_deadline: daysFromNow(44), remote_allowed:0, description:'Teach advanced cyber law specialization.', responsibilities:'Lectures; Moots; Policy research', requirements:'Relevant publications', benefits:'Conference travel', salary_min:70000, salary_max:110000 }
];

const allJobs = [...initialJobs, ...additionalJobs];
const toInsert = allJobs.filter(j => !existingTitles.has(j.title));

if (!toInsert.length) {
  console.log('All predefined jobs already present. No new rows inserted.');
  process.exit(0);
}

const insert = db.prepare(`INSERT INTO jobs (employer_id,title,description,subject,grade_level,location,salary_min,salary_max,status,organization_type,institution_name,employment_type,min_experience,education_required,skills_required,application_deadline,responsibilities,requirements,pay_scale,benefits,organization_website,city,remote_allowed) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);
const insertMany = db.transaction((rows)=>{ for (const j of rows){ insert.run(employer.id,j.title,j.description,j.subject,j.grade_level,j.location,j.salary_min,j.salary_max,'approved',j.organization_type,j.institution_name,j.employment_type,j.min_experience,j.education_required,j.skills_required,j.application_deadline,j.responsibilities,j.requirements,j.pay_scale,j.benefits,j.organization_website||null,j.city,j.remote_allowed); }});
insertMany(toInsert);
console.log('Inserted', toInsert.length, 'new job records (total predefined:', allJobs.length, ').');